### PR TITLE
High five!

### PR DESCRIPTION
**Pull request by ViliamVadocz**
might not work on linux ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by AnarchyHelper** [comment]
This pull request has not been merged as you have edited a file not in the `anarchy` folder.

**Comment by AnarchyHelper** [comment]
This pull request has not been merged as you have edited a file not in the `anarchy` folder.

**Comment by AnarchyHelper** [comment]
This pull request has not been merged as you have edited a file not in the `anarchy` folder.

**Comment by ViliamVadocz** [comment]
ok I get it! >:(

**Pull request merged**
