### PR TITLE
Triple Threat

### PR DESCRIPTION
**Pull request by robbai**

### CODE REVIEW

**Comment by AnarchyHelper** [comment]
This pull request cannot be merged as you have exceeded your limit of 100 lines of additions.
You currently have 31 addition(s) left and 50 deletion(s) left.

**Comment by robbai** [comment]
I thought I regained them by now 😠

**Comment by Darxeal** [comment]
F

**Comment by TheBlocks** [comment]
F

**Comment by TheBlocks** [comment]
Un F

**Pull request merged**
